### PR TITLE
TASK: Add Codeblocks to README.md

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by gurusabarish** [comment]
Hi @crydotsnake 
Your pull request has minor updates and I think this is not really important one at this time.
If you really want create a pull request, then create a documentation for this template. Please, make a separate folder docs and place your all readme files within that folder.

Thank you for the commit ❤️

**Comment by crydotsnake** [comment]
This has nothing to do with documentaion 🤔?

**Comment by crydotsnake** [comment]
This PR is for the `README.md` to make the YAML Code look nicer ;).

**Comment by gurusabarish** [comment]
> 
> 
> This PR is for the `README.md` to make the YAML Code look nicer ;).

I agree, But we changed readme code-blocks, then the look of the blocks also change in [website](https://themes.gohugo.io/hugo-profile/). That's why I don't.

>This has nothing to do with documentaion 🤔?

We can document on,
- how to use this theme with hugo?
- How edit your data?
- how to deploy?

*Note: I will bring some new features in two weeks.*

**Pull request closed without merging**
