### PR TITLE
[resolves #92] make navbar sticky

### LINKED ISSUE #92: Sticky navbar
Please add the option to make the navbar sticky, or make it default.

Thanks!

### PR DESCRIPTION
**Pull request by pantera-rosa**
bandaid fix for sticky navbar. note that this makes a sticky navbar the default. can also add a flag to enable/disable based on user preference, although sticky navbar is generally good practice regardless 

demo:
https://user-images.githubusercontent.com/15808601/217377698-9dd2b2dd-8047-451d-863b-ad4bde79ee00.mov

### CODE REVIEW

**Comment by LITUATUI** [comment]
It looks good.

**Review by benarmstead — APPROVED** [review]

**Comment by benarmstead** [comment]
Should this be optional with a flag in the `config.yml`?

**Comment by gurusabarish** [comment]
> Should this be optional with a flag in the config.yml?

Yes, @benarmstead 

----------

And @pantera-rosa please, check other pages behaviour over index page.
https://deploy-preview-100--hugo-profile.netlify.app/

**Comment by benarmstead** [comment]
@pantera-rosa @gurusabarish 
Created a PR: https://github.com/pantera-rosa/hugo-profile/pull/1/files, into this branch to make it optional.

**Comment by pantera-rosa** [comment]
thanks @benarmstead!

**Comment by gurusabarish** [comment]
Sticky navbar support added in https://github.com/gurusabarish/hugo-profile/commit/70ea254099da0239185824c04adf77af33aafa7a for all pages

**Comment by delize** [comment]
@gurusabarish 

Looking back through this, there seems to be an issue in the class, the commit you made: https://github.com/gurusabarish/hugo-profile/blame/master/layouts/partials/sections/header.html#L33:

`profileHeaderElem.classList.add("showHeaderOnTop");`\

Adds a custom class that does not work properly with a sticky navbar. 

Where the original PR made the correct class:
https://github.com/gurusabarish/hugo-profile/pull/100/files#diff-71f0045cd057a8a32a4f7ffead11e64f44558e9d0e3d01afe65d9c7c0048e819R27

When changing this back to fixed-top based on: https://mdbootstrap.com/learn/mdb-foundations/mdb-ui-kit/sticky-navbar/

This resolves the issue. 

This behavior that I commented on in #92 , can also be seen on your netlify demo app site.

**Pull request closed without merging**
