### PR TITLE
Statics param, and optional GPA

### PR DESCRIPTION
**Pull request by sonic182**
Statics param, to allow websites in a sub-path like `<ghuser-or-org>.github.io/myhugosite/`

Also, optional GPA for Education section

### CODE REVIEW

**Comment by gurusabarish** [comment]
Hi @sonic182, 

This feature is a needed one. Thanks for the pull request. I made some changes like,
- Renamed `statics` to `staticPath`
- Added `staticPath` in missed files

Please, take a look.

Thanks for your valuable time ❤️

**Comment by sonic182** [comment]
Seems nice! Some files lack the change from Statics to StaticPath, I'm in my phone, hope to tune the PR when I get into the PC

**Comment by sonic182** [comment]
Hi @gurusabarish

I think it is complete now 😀

**Comment by gurusabarish** [comment]
Thanks @sonic182 ❤️

**Pull request merged**
