### PR TITLE
set automatically dark mode

### PR DESCRIPTION
**Pull request by lr1980**

### CODE REVIEW

**Comment by gurusabarish** [comment]
Hii @lr1980, you done an **amazing job**. Thanks for your all pull requests and your valuable time.

I think, it's not working. Please, take a look if possible
https://deploy-preview-37--hugo-profile.netlify.app/

**Comment by lr1980** [comment]
For me (MacOS + Safari/Firefox/Chrome) it is working... I used this information for that change: 
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by gurusabarish** [comment]
It's working. Thanks @lr1980 
Could you make same changes here? It will be reflected to the list and single pages.
https://github.com/lr1980/hugo-profile/blob/automatic-dark-mode/layouts/_default/baseof.html

**Comment by lr1980** [comment]
I'm currently a bit busy, but I'll stay tuned....

**Comment by abe-101** [comment]
On my browser this works (linux/firefox) but strange thing is, when i go to blog it isn't dark mode. Do we need to make changes for blog html file?

**Review by abe-101 — APPROVED** [review]

**Comment by gurusabarish** [comment]
> but strange thing is, when i go to blog it isn't dark mode. Do we need to make changes for blog html file?

Blog page is dependent on https://github.com/gurusabarish/hugo-profile/blob/a1a2264e6bb81102b297e9e1838d4777f9460c97/layouts/_default/baseof.html. That's why dark mode is not working in blog. 

We should add the same in baseof.html to fix

**Comment by lr1980** [comment]
Please check my changes... I have also added a dark mode cookie.

**Review by abe-101 — APPROVED** [review]

**Comment by gurusabarish** [comment]
Hii @lr1980 

Thanks for the pull request and time. This is not working as expected. So, I fixed in #45 

#37 demo: https://deploy-preview-37--hugo-profile.netlify.app/
#45 demo: https://deploy-preview-45--hugo-profile.netlify.app/

**Pull request closed without merging**
